[posterazor]
source = "regex"
url = "https://github.com/aportale/posterazor/branches/all?query=PosteRazor_"
regex = 'PosteRazor_(\d+_\d+_\d+)\.*'
from_pattern = '(\d+)_(\d+)_(\d+)'
to_pattern = '\1.\2.\3'
