version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    ".nvchecker.toml",
    "simplify-wrapper-scripts.patch",
	  "update-restart-cfg.patch",
	  "use-uaccess-for-udev.patch",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"
