[openbao-plugin-secrets-aws]
source = "git"
git = "https://github.com/openbao/openbao-plugins.git"
prefix = "secrets-aws-v"
include_regex = "secrets-aws-v.*"
exclude_regex = ".*(pre|alpha|b|beta|rc).*"
