[libb64]
source = "htmlparser"
url = "https://sourceforge.net/projects/libb64/files/libb64/libb64/"
xpath = "//*[@id=\"files_list\"]/tbody/tr/th/a/span"
from_pattern = "libb64-((?:\\d+\\.)*\\d+)\\.zip"
to_pattern = "\\1"

