[opengl-man-pages]
# source = "git"
# git = "https://github.com/KhronosGroup/OpenGL-Refpages.git"
# use_commit = true
source = "github"
github = "KhronosGroup/OpenGL-Refpages"
from_pattern = '(\d+).(\d+)'
to_pattern = '\1'
