d /var/lib/audiobookshelf 0755 audiobookshelf audiobookshelf
d /var/lib/audiobookshelf/metadata 0755 audiobookshelf audiobookshelf
d /var/lib/audiobookshelf/config 0755 audiobookshelf audiobookshelf
d /var/lib/audiobookshelf/backup 0755 audiobookshelf audiobookshelf
Z /var/lib/audiobookshelf - audiobookshelf audiobookshelf
f /etc/audiobookshelf.env 0640 audiobookshelf audiobookshelf
