version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    ".nvchecker.toml",
    "js80p.install",
    "do-not-run-cppcheck.patch",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"
