version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "sysusers.conf",
    "tmpfiles.conf",
    "systemd.service",
    "config.env",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "version-strings.patch",
]
SPDX-FileCopyrightText = "opencloud contributors"
SPDX-License-Identifier = "Apache-2.0"
