version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.sh",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "com.super_productivity.SuperProductivity.metainfo.xml",
    "0001-fix-linux-set-desktop-name-to-fix-icon-on-Wayland.patch",
    "0002-build-exclude-wayland-idle-helper-from-asar-archive.patch",
]
SPDX-FileCopyrightText = "Super Productivity contributors"
SPDX-License-Identifier = "MIT"
