version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "devendor-libs.patch",
    "ftbfs-werror.patch",
    "improve-reproducibility.patch",
]
SPDX-FileCopyrightText = "surge-xt contributors"
SPDX-License-Identifier = "GPL-3.0-only"
