[ibus-table-extraphrase]
source = "regex"
url = "https://storage.googleapis.com/storage/v1/b/google-code-archive/o/v2%2Fcode.google.com%2Fibus%2Fdownloads-page-4.json?alt=media"
regex = "ibus-table-extraphrase-([0-9\\.]+).tar.gz"
