Alias /roundcube "/usr/share/webapps/roundcubemail/public_html"
<Directory "/usr/share/webapps/roundcubemail/public_html">
    AllowOverride All
    Options FollowSymlinks
    Require all granted
    php_admin_value open_basedir "/tmp/:/var/cache/roundcubemail:/usr/share/webapps/roundcubemail:/etc/webapps/roundcubemail:/usr/share/pear/:/var/log/roundcubemail"
</Directory>
