[mythes-en]
source = "regex"
# url = "https://cgit.freedesktop.org/libreoffice/dictionaries/log/en"
url = "https://cgit.freedesktop.org/libreoffice/dictionaries/atom/en?h=master"
regex = '(\d{4}-\d{2}-\d{2})'
from_pattern = '(\d+)-(\d+)-(\d+)'
to_pattern = '\1\2\3'
