version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    "stalwart.install",
    ".nvchecker.toml",
    "sysusers.conf",
    "tmpfiles.conf",
    "systemd.service",
    "config.env",
    "use-local-webui-archive.patch",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"
