[hyphen-de]
source = "regex"
regex = "Version: ([\\d-]+)"
url = "https://extensions.libreoffice.org/en/extensions/show/german-de-de-frami-dictionaries"
from_pattern = '(\d+)-(\d+)-(\d+)'
to_pattern = '\1\2\3'
