version = 1

[[annotations]]
path = ["learning-algol-68-genie.pdf"]
SPDX-FileCopyrightText = "Marcel van der Veer 2008-2026"
SPDX-License-Identifier = "GFDL-1.2-or-later"

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"
