version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "xkbsel-0.13-autotools.patch",
    "xkbsel-0.13-gdbm.patch",
    "xkbsel-0.13-incompatible-pointer-types.patch",
    "xkbsel-0.13-install.patch",
    "xkbsel-0.13-x11xkbdir.patch",
]
SPDX-FileCopyrightText = "xkbsel contributors"
SPDX-License-Identifier = "GPL-2.0-only"
