# Upstream's versioning is a complete mess; This is the best I could find.
[ttf-lato]
source = "regex"
regex = '\#+ Version ([\d.]+) \(\d+-\d+-\d+\)'
url = "https://raw.githubusercontent.com/latofonts/lato-source/refs/heads/master/README.md"
