[splint]
#source = "git"
#git = "https://repo.or.cz/splint-patched.git"
#prefix = "splint-"

source = "regex"
url = "https://repo.or.cz/splint-patched.git/refs"
regex = "heads/splint-(\\d+_\\d+_\\d+)<"
from_pattern = "_"
to_pattern = "."
