[docbook-mathml]
#source = "github"
#github = "docbook/dsssl"
#use_max_tag = true
#ignore = "SVNSNAPSHOT"

source = "regex"
regex = "V(\\d+.\\d+CR1)"
# url = "https://docbook.org/specs/"
url = "https://archive.docbook.org/xml/mathml/1.1CR1/"
