[usb_modeswitch]
source = "htmlparser"
is_xml=true
url = "https://www.draisberghof.de/usb_modeswitch/usb-modeswitch-versions.xml"
xpath = "//xml"
from_pattern = "\\s+([\\d\\.]+)\\s+.+\\s+(\\d{8})\\s+.*"
to_pattern = "\\1.\\2"
