version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
    "inn-2.7.4-disable-installing-files-using-the-owner-and-group-we-also-run-as.patch",
    "inn-first-run",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"
