[ibus-unikey]
source = "regex"
url = "https://storage.googleapis.com/storage/v1/b/google-code-archive/o/v2%2Fcode.google.com%2Fibus-unikey%2Fdownloads-page-1.json?alt=media"
regex = "ibus-unikey-([0-9\\.]+).tar.gz"
