[markdownlint-sentences-per-line]
source = "git"
git = "https://github.com/JoshuaKGoldberg/sentences-per-line.git"
prefix = "markdownlint-sentences-per-line@v"
include_regex = "markdownlint-sentences-per-line@v[\\d.]+"
