f /etc/stalwart/proxy/config.toml 0640 stalwart-proxy stalwart-proxy
f /etc/stalwart/proxy/mappings.tsv 0640 stalwart-proxy stalwart-proxy
f /etc/stalwart/proxy/config.env 0640 root stalwart-proxy
f /etc/stalwart/proxy/admin.token 0640 root stalwart-proxy
d /etc/stalwart/proxy 0750 stalwart-proxy stalwart-proxy
d /etc/stalwart/proxy/tls 0750 stalwart-proxy stalwart-proxy
d /var/log/stalwart-proxy 0750 stalwart-proxy stalwart-proxy
