#Type Path                                     Mode   User Group Age         Argument
f     /var/lib/informant.dat                   0664   root informant - -
d     /var/cache/informant                     2775   root informant - -
