[ext3grep]
source = "regex"
url = "https://storage.googleapis.com/storage/v1/b/google-code-archive/o/v2%2Fcode.google.com%2Fext3grep%2Fdownloads-page-1.json?alt=media"
regex = 'ext3grep-([\d.]+).tar.gz'
