[xtrabackup]
source = "jq"
user_agent = "curl/8.19.0"
url = "https://www.percona.com/wp-admin/admin-ajax.php"
post_data = "action=percona_downloads&product_id=Percona-XtraBackup-8.4&hydrate=1"
post_data_type = "application/x-www-form-urlencoded"
filter = ".data.versions[0]"
prefix = "Percona-XtraBackup-"
from_pattern = "-"
to_pattern = "_"
