# nvchecker's source=git does not differentiate between
# pre release or latest release, please manually verify
# tags against the two repositories mentioned in
# PKGBUILD
[vaultwarden-web]
source = 'github'
github = 'dani-garcia/bw_web_builds'
use_latest_release = true
prefix = 'v'
