[docbook5-xml]
#source = "github"
#github = "docbook/dsssl"
#use_max_tag = true
#ignore = "SVNSNAPSHOT"

source = "regex"
# regex = "DocBook Version (\\d.+)[,]"
regex = "DocBook V(\\d.+\\d+) "
# url = "https://docbook.org/specs/"
url = "https://archive.docbook.org/xml/5.1/"
