version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0001-do-not-load-binary-modules-for-dkms-package.patch",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "GPL-2.0-only"

[[annotations]]
path = [
    "82033542e7bf14e4fbaad6a525bf6763f9d9f840.patch",
    "c6fa96409925203569f1ec5f95ac1544fa691548.patch",
    "eeec50f6896c7d52f5fc22c7a3699cbd783a767c.patch",
]
SPDX-FileCopyrightText = "Bcachefs contributors"
SPDX-License-Identifier = "GPL-2.0-only"
